/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author BrunoDev
 */
public class Ventana1 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        texNumero2 = new javax.swing.JTextField();
        texNumero1 = new javax.swing.JTextField();
        tesResultado = new javax.swing.JLabel();
        btnRestar = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        btnMurtiplicar = new javax.swing.JButton();
        tesResultado1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 450));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(30, 30, 30));
        jPanel2.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(680, 450));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Numero2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Numero1");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        texNumero2.setBackground(new java.awt.Color(50, 50, 50));
        texNumero2.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        texNumero2.setForeground(new java.awt.Color(255, 255, 255));
        texNumero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));
        texNumero2.setCaretColor(new java.awt.Color(255, 255, 255));
        texNumero2.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        texNumero2.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(texNumero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 240, 45));

        texNumero1.setBackground(new java.awt.Color(50, 50, 50));
        texNumero1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        texNumero1.setForeground(new java.awt.Color(255, 255, 255));
        texNumero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 60, 60), 2));
        texNumero1.setCaretColor(new java.awt.Color(255, 255, 255));
        texNumero1.setSelectedTextColor(new java.awt.Color(153, 153, 153));
        texNumero1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(texNumero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 240, 45));

        tesResultado.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        tesResultado.setForeground(new java.awt.Color(255, 255, 255));
        tesResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(tesResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 580, 50));

        btnRestar.setBackground(new java.awt.Color(102, 102, 102));
        btnRestar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnRestar.setForeground(new java.awt.Color(255, 255, 255));
        btnRestar.setText("Restar()");
        jPanel2.add(btnRestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 250, -1));

        btnSumar.setBackground(new java.awt.Color(102, 102, 102));
        btnSumar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnSumar.setForeground(new java.awt.Color(255, 255, 255));
        btnSumar.setText("Sumar()");
        jPanel2.add(btnSumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 250, -1));

        btnDividir.setBackground(new java.awt.Color(102, 102, 102));
        btnDividir.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnDividir.setForeground(new java.awt.Color(255, 255, 255));
        btnDividir.setText("Dividir()");
        jPanel2.add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 250, -1));

        btnMurtiplicar.setBackground(new java.awt.Color(102, 102, 102));
        btnMurtiplicar.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        btnMurtiplicar.setForeground(new java.awt.Color(255, 255, 255));
        btnMurtiplicar.setText("Murtiplicar()");
        jPanel2.add(btnMurtiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 250, -1));

        tesResultado1.setFont(new java.awt.Font("Verdana", 0, 60)); // NOI18N
        tesResultado1.setForeground(new java.awt.Color(0, 102, 255));
        tesResultado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tesResultado1.setText("Tests JUnit");
        jPanel2.add(tesResultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 580, 70));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 680;
        gridBagConstraints.ipady = 450;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel1.add(jPanel2, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnDividir() {
        return btnDividir;
    }

    public JButton getBtnMurtiplicar() {
        return btnMurtiplicar;
    }

    public JButton getBtnRestar() {
        return btnRestar;
    }

    public JButton getBtnSumar() {
        return btnSumar;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public JLabel getTesResultado() {
        return tesResultado;
    }

    public JTextField getTexNumero1() {
        return texNumero1;
    }

    public JTextField getTexNumero2() {
        return texNumero2;
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMurtiplicar;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel tesResultado;
    private javax.swing.JLabel tesResultado1;
    private javax.swing.JTextField texNumero1;
    private javax.swing.JTextField texNumero2;
    // End of variables declaration//GEN-END:variables
}
